"""
A complete (unrunable) LLaMA-style decoder-only Transformer code generated by DeepSeek (not me, atleast for now)
that I cant run locally because I only have 8GB RAM and ryzen 3 iGPU and its solely purpose is to understand 
how the code would typically looks like
:
  * RMSNorm, RoPE, SwiGLU, Grouped-Query Attention (GQA)
  * Fast attention via F.scaled_dot_product_attention (FlashAttention under the hood)
  * KV-cache for fast autoregressive decoding
  * Full training loop: AdamW, warmup+cosine LR, AMP (bf16/fp16), grad clipping,
    gradient accumulation, periodic eval, checkpointing, torch.compile support
  * Sampling: temperature / top-k / top-p / repetition penalty, optional greedy
  * A tiny built-in corpus + char-level tokenizer so it runs out of the box

Usage
-----
    python transformer-e2e.py                                                  # train a demo + sample text
    python transformer-e2e.py --mode train                                     # train only
    python transformer-e2e.py --mode generate --prompt "The "
    python transformer-e2e.py --data my_corpus.txt --max-steps 5000 --dim 384
    python transformer-e2e.py --mode generate --temperature 0.7 --top-k 40
"""

import argparse
import contextlib
import math
import os
import time
from dataclasses import dataclass, asdict
from typing import Optional, Tuple, List, Dict, Any

import torch
import torch.nn as nn
import torch.nn.functional as F


# 0. Built-in demo corpus 
SAMPLE_TEXT = """The lighthouse keeper rose before the sun, as he had every morning for thirty years.
He climbed the spiral stair with a lantern in one hand and a cup of black coffee in the other,
counting the steps out of habit: one hundred and forty-four, always the same, always cold.
At the top the great lamp waited, patient as an old dog, and he set to work polishing the glass
until the sea itself seemed to lean in and look back at him.

Below the cliff the village was still asleep. Fishing boats lay tangled in their moorings,
and the gulls had not yet begun to argue over the morning's first catch. He liked this hour,
when the world was only a rumor of itself and nothing had gone wrong yet.

There was a storm coming. He could feel it in the ache of his left knee and in the way the
wind kept changing its mind. By noon the sky had turned the color of wet slate, and the first
heavy drops began to strike the glass like small fists. He lit the lamp early that day.

The ships came in one by one, running before the weather with their lights low and their
engines straining. He counted them as they passed the point: the Marigold, the Fair Wind,
the little blue trawler that belonged to the widow on the hill. When the last one slipped
into the harbor he let out a breath he did not know he had been holding.

That night the storm broke everything it could reach. Waves climbed the cliff and threw
themselves against the tower, and the wind screamed in the railings like something alive.
But the lamp burned steady, and the light went out over the water in long slow sweeps,
and every sailor for twenty miles knew exactly where the rocks were.

In the morning the sea was flat and innocent, as if it had never done anything wrong in
its life. The keeper walked down to the village and drank tea in the warm kitchen of the
widow on the hill, and they did not say much, because there was not much that needed saying.

He climbed the stair again at dusk. One hundred and forty-four steps. The lamp was waiting.
It was always waiting. That, he thought, was the whole of it: the light does not ask whether
the night deserves it. The light simply burns, and the ships come home.
"""


# 1. Configuration
@dataclass
class ModelArgs:
    dim: int = 256
    n_layers: int = 6
    n_heads: int = 8
    n_kv_heads: Optional[int] = 4          # Grouped-Query Attention (None -> MHA)
    vocab_size: int = 32000
    multiple_of: int = 256                 # SwiGLU hidden size is a multiple of this
    ffn_dim_multiplier: Optional[float] = None
    norm_eps: float = 1e-5
    max_batch_size: int = 32
    max_seq_len: int = 256
    dropout: float = 0.0
    tie_embeddings: bool = True


@dataclass
class TrainConfig:
    batch_size: int = 32
    grad_accum_steps: int = 1
    max_steps: int = 1500
    eval_interval: int = 100
    eval_iters: int = 40
    log_interval: int = 10
    lr: float = 1e-3
    min_lr: float = 1e-4
    warmup_steps: int = 100
    weight_decay: float = 0.1
    beta1: float = 0.9
    beta2: float = 0.95
    grad_clip: float = 1.0
    device: str = "auto"
    dtype: str = "auto"                    # auto | bfloat16 | float16 | float32
    compile: bool = False
    out_dir: str = "out"
    seed: int = 1337


# 2. Core layers
class RMSNorm(nn.Module):
    """Root-mean-square layer norm (no mean subtraction, no bias)."""

    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def _norm(self, x: torch.Tensor) -> torch.Tensor:
        # Computed in fp32 for stability, even under autocast.
        variance = x.pow(2).mean(-1, keepdim=True)
        return x * torch.rsqrt(variance + self.eps)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        output_dtype = x.dtype
        x = x.to(torch.float32)
        x_norm = self._norm(x)
        return (x_norm * self.weight).to(output_dtype)


def precompute_freqs_cis(dim: int, end: int, theta: float = 10000.0) -> torch.Tensor:
    """Precompute cos + i*sin for rotary position embeddings."""
    freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
    t = torch.arange(end, device=freqs.device, dtype=torch.float32)
    freqs = torch.outer(t, freqs).float()
    return torch.polar(torch.ones_like(freqs), freqs)   # complex64


def reshape_for_broadcast(freqs_cis: torch.Tensor, x: torch.Tensor) -> torch.Tensor:
    ndim = x.ndim
    assert 0 <= 1 < ndim
    assert freqs_cis.shape == (x.shape[1], x.shape[-1]), (
        f"freqs_cis {tuple(freqs_cis.shape)} vs x {tuple(x.shape)}"
    )
    shape = [d if i == 1 or i == ndim - 1 else 1 for i, d in enumerate(x.shape)]
    return freqs_cis.view(*shape)


def apply_rotary_emb(
    xq: torch.Tensor,
    xk: torch.Tensor,
    freqs_cis: torch.Tensor,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Rotate query/key vectors in the complex plane. Shapes: (B, S, H, D)."""
    xq_ = torch.view_as_complex(xq.float().reshape(*xq.shape[:-1], -1, 2))
    xk_ = torch.view_as_complex(xk.float().reshape(*xk.shape[:-1], -1, 2))
    freqs_cis = reshape_for_broadcast(freqs_cis, xq_)
    xq_out = torch.view_as_real(xq_ * freqs_cis).flatten(3)
    xk_out = torch.view_as_real(xk_ * freqs_cis).flatten(3)
    return xq_out.type_as(xq), xk_out.type_as(xk)


class KVCache:
    """Per-layer key/value cache for incremental decoding."""

    __slots__ = ("k", "v")

    def __init__(self):
        self.k: Optional[torch.Tensor] = None
        self.v: Optional[torch.Tensor] = None

    def update(self, k: torch.Tensor, v: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        if self.k is None:
            self.k, self.v = k, v
        else:
            self.k = torch.cat([self.k, k], dim=2)
            self.v = torch.cat([self.v, v], dim=2)
        return self.k, self.v

    def reset(self):
        self.k = None
        self.v = None

    @property
    def size(self) -> int:
        return 0 if self.k is None else self.k.size(2)


class Attention(nn.Module):
    """Multi-head / grouped-query causal self-attention with RoPE."""

    def __init__(self, args: ModelArgs):
        super().__init__()
        self.n_kv_heads = args.n_heads if args.n_kv_heads is None else args.n_kv_heads
        assert args.n_heads % self.n_kv_heads == 0, "n_heads must be divisible by n_kv_heads"
        self.n_local_heads = args.n_heads
        self.n_local_kv_heads = self.n_kv_heads
        self.n_rep = self.n_local_heads // self.n_local_kv_heads
        self.head_dim = args.dim // args.n_heads
        assert self.head_dim % 2 == 0, "head_dim must be even for RoPE"
        self.dropout = args.dropout

        self.wq = nn.Linear(args.dim, args.n_heads * self.head_dim, bias=False)
        self.wk = nn.Linear(args.dim, self.n_kv_heads * self.head_dim, bias=False)
        self.wv = nn.Linear(args.dim, self.n_kv_heads * self.head_dim, bias=False)
        self.wo = nn.Linear(args.n_heads * self.head_dim, args.dim, bias=False)

    def forward(
        self,
        x: torch.Tensor,
        freqs_cis: torch.Tensor,
        mask: Optional[torch.Tensor] = None,
        cache: Optional[KVCache] = None,
    ) -> torch.Tensor:
        bsz, seqlen, _ = x.shape

        xq = self.wq(x).view(bsz, seqlen, self.n_local_heads, self.head_dim)
        xk = self.wk(x).view(bsz, seqlen, self.n_local_kv_heads, self.head_dim)
        xv = self.wv(x).view(bsz, seqlen, self.n_local_kv_heads, self.head_dim)

        # RoPE is applied only to the *new* tokens (freqs_cis matches seqlen).
        xq, xk = apply_rotary_emb(xq, xk, freqs_cis=freqs_cis)

        # (B, S, H, D) -> (B, H, S, D)
        xq = xq.transpose(1, 2)
        xk = xk.transpose(1, 2)
        xv = xv.transpose(1, 2)

        # Append to cache (cache holds un-expanded KV heads to save memory).
        if cache is not None:
            xk, xv = cache.update(xk, xv)

        # Expand KV heads to match query heads for GQA.
        if self.n_rep > 1:
            xk = xk.repeat_interleave(self.n_rep, dim=1)
            xv = xv.repeat_interleave(self.n_rep, dim=1)

        dropout_p = self.dropout if self.training else 0.0

        if mask is not None:
            out = F.scaled_dot_product_attention(xq, xk, xv, attn_mask=mask, dropout_p=dropout_p)
        else:
            # Causal masking is only needed for a full (prefill) pass; a single
            # query token attending to the whole cache is causal by construction.
            is_causal = xq.size(2) > 1 and xq.size(2) == xk.size(2)
            out = F.scaled_dot_product_attention(
                xq, xk, xv, is_causal=is_causal, dropout_p=dropout_p
            )

        out = out.transpose(1, 2).contiguous().view(bsz, seqlen, -1)
        return self.wo(out)


class FeedForward(nn.Module):
    """SwiGLU feed-forward network."""

    def __init__(self, dim: int, hidden_dim: int, multiple_of: int,
                 ffn_dim_multiplier: Optional[float], dropout: float = 0.0):
        super().__init__()
        hidden_dim = int(2 * hidden_dim / 3)
        if ffn_dim_multiplier is not None:
            hidden_dim = int(ffn_dim_multiplier * hidden_dim)
        hidden_dim = multiple_of * ((hidden_dim + multiple_of - 1) // multiple_of)

        self.w1 = nn.Linear(dim, hidden_dim, bias=False)   # gate
        self.w2 = nn.Linear(hidden_dim, dim, bias=False)   # down
        self.w3 = nn.Linear(dim, hidden_dim, bias=False)   # up
        self.drop = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.drop(self.w2(F.silu(self.w1(x)) * self.w3(x)))


class TransformerBlock(nn.Module):
    def __init__(self, layer_id: int, args: ModelArgs):
        super().__init__()
        self.layer_id = layer_id
        self.n_heads = args.n_heads
        self.dim = args.dim
        self.head_dim = args.dim // args.n_heads

        self.attention = Attention(args)
        self.feed_forward = FeedForward(
            dim=args.dim,
            hidden_dim=4 * args.dim,
            multiple_of=args.multiple_of,
            ffn_dim_multiplier=args.ffn_dim_multiplier,
            dropout=args.dropout,
        )
        self.attention_norm = RMSNorm(args.dim, eps=args.norm_eps)
        self.ffn_norm = RMSNorm(args.dim, eps=args.norm_eps)
        self.resid_drop = nn.Dropout(args.dropout)

    def forward(
        self,
        x: torch.Tensor,
        freqs_cis: torch.Tensor,
        mask: Optional[torch.Tensor] = None,
        cache: Optional[KVCache] = None,
    ) -> torch.Tensor:
        h = x + self.resid_drop(self.attention(self.attention_norm(x), freqs_cis, mask, cache))
        out = h + self.resid_drop(self.feed_forward(self.ffn_norm(h)))
        return out


class Transformer(nn.Module):
    def __init__(self, params: ModelArgs):
        super().__init__()
        self.params = params
        self.vocab_size = params.vocab_size
        self.n_layers = params.n_layers

        self.tok_embeddings = nn.Embedding(params.vocab_size, params.dim)
        self.drop = nn.Dropout(params.dropout)

        self.layers = nn.ModuleList(
            [TransformerBlock(layer_id, params) for layer_id in range(params.n_layers)]
        )

        self.norm = RMSNorm(params.dim, eps=params.norm_eps)
        self.output = nn.Linear(params.dim, params.vocab_size, bias=False)

        # RoPE table: 2x max_seq_len so generation can run past the training window.
        self.register_buffer(
            "freqs_cis",
            precompute_freqs_cis(
                params.dim // params.n_heads, params.max_seq_len * 2
            ),
            persistent=False,
        )

        self.apply(self._init_weights)
        self._scale_residual_projections()

        if params.tie_embeddings:
            self.output.weight = self.tok_embeddings.weight

    # -- initialization ----------------------------------------------------
    def _init_weights(self, module: nn.Module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def _scale_residual_projections(self):
        """GPT-2 style scaling of the output projections of residual branches."""
        std = 0.02 / math.sqrt(2 * self.n_layers)
        for name, p in self.named_parameters():
            if name.endswith("wo.weight") or name.endswith("w2.weight"):
                torch.nn.init.normal_(p, mean=0.0, std=std)

    # -- forward -----------------------------------------------------------
    def forward(
        self,
        tokens: torch.Tensor,
        start_pos: int = 0,
        caches: Optional[List[KVCache]] = None,
        targets: Optional[torch.Tensor] = None,
        ignore_index: int = -100,
    ):
        """
        tokens   : (B, S) int64
        start_pos: absolute position of tokens[:, 0] (used with KV cache)
        caches   : list of KVCache, one per layer, or None
        targets  : (B, S) int64 -> returns (full_logits, loss)
                   None        -> returns (logits_for_last_position, None)
        """
        _bsz, seqlen = tokens.shape

        h = self.drop(self.tok_embeddings(tokens))

        if start_pos + seqlen > self.freqs_cis.shape[0]:
            raise ValueError(
                f"position {start_pos + seqlen} exceeds RoPE table "
                f"({self.freqs_cis.shape[0]}). Increase max_seq_len."
            )
        freqs_cis = self.freqs_cis[start_pos: start_pos + seqlen]

        for i, layer in enumerate(self.layers):
            cache = None if caches is None else caches[i]
            h = layer(h, freqs_cis, mask=None, cache=cache)

        h = self.norm(h)

        if targets is not None:
            logits = self.output(h)
            loss = F.cross_entropy(
                logits.view(-1, logits.size(-1)),
                targets.reshape(-1),
                ignore_index=ignore_index,
            )
            return logits, loss

        # Inference: only the last position is needed to predict the next token.
        logits = self.output(h[:, -1:, :])
        return logits, None

    @property
    def num_params(self) -> int:
        return sum(p.numel() for p in self.parameters())

    @property
    def num_params_non_embedding(self) -> int:
        n = self.num_params - self.tok_embeddings.weight.numel()
        if not self.params.tie_embeddings:
            n -= self.output.weight.numel()
        return n


# 3. Tokenizer
class CharTokenizer:
    """Minimal character-level tokenizer (no external dependencies)."""

    def __init__(self, text: Optional[str] = None, chars: Optional[str] = None):
        if chars is not None:
            self.chars = list(chars)
        elif text is not None:
            self.chars = sorted(set(text))
        else:
            raise ValueError("Provide either `text` or `chars`.")
        self.stoi = {c: i for i, c in enumerate(self.chars)}
        self.itos = {i: c for i, c in enumerate(self.chars)}

    @property
    def vocab_size(self) -> int:
        return len(self.chars)

    def encode(self, s: str) -> List[int]:
        return [self.stoi[c] for c in s if c in self.stoi]

    def decode(self, ids) -> str:
        if torch.is_tensor(ids):
            ids = ids.tolist()
        return "".join(self.itos[int(i)] for i in ids)

    def state_dict(self) -> Dict[str, Any]:
        return {"chars": "".join(self.chars)}

    @classmethod
    def from_state_dict(cls, sd: Dict[str, Any]) -> "CharTokenizer":
        return cls(chars=sd["chars"])

# 4. Data utilities
def load_text(path: Optional[str]) -> str:
    if path:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return SAMPLE_TEXT


def split_train_val(data: torch.Tensor, val_frac: float = 0.1) -> Tuple[torch.Tensor, torch.Tensor]:
    n = int(len(data) * (1.0 - val_frac))
    n = max(n, 1)
    return data[:n], data[n:]


def get_batch(
    data: torch.Tensor, block_size: int, batch_size: int, device: torch.device
) -> Tuple[torch.Tensor, torch.Tensor]:
    if len(data) <= block_size + 1:
        raise ValueError(
            f"Corpus too small ({len(data)} tokens) for block_size={block_size}."
        )
    ix = torch.randint(0, len(data) - block_size - 1, (batch_size,))
    x = torch.stack([data[i: i + block_size] for i in ix])
    y = torch.stack([data[i + 1: i + 1 + block_size] for i in ix])
    return x.to(device, non_blocking=True), y.to(device, non_blocking=True)

# 5. Training utilities
def resolve_device(requested: str) -> torch.device:
    if requested == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    return torch.device(requested)


def resolve_dtype(requested: str, device: torch.device) -> torch.dtype:
    if requested == "auto":
        if device.type == "cuda":
            return torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
        return torch.float32
    return {
        "bfloat16": torch.bfloat16,
        "bf16": torch.bfloat16,
        "float16": torch.float16,
        "fp16": torch.float16,
        "float32": torch.float32,
        "fp32": torch.float32,
    }[requested]


def get_lr(step: int, cfg: TrainConfig) -> float:
    """Linear warmup followed by cosine decay."""
    if step < cfg.warmup_steps:
        return cfg.lr * (step + 1) / max(1, cfg.warmup_steps)
    if step >= cfg.max_steps:
        return cfg.min_lr
    ratio = (step - cfg.warmup_steps) / max(1, cfg.max_steps - cfg.warmup_steps)
    coeff = 0.5 * (1.0 + math.cos(math.pi * ratio))
    return cfg.min_lr + coeff * (cfg.lr - cfg.min_lr)


def build_optimizer(model: nn.Module, cfg: TrainConfig) -> torch.optim.Optimizer:
    """AdamW with weight decay only on matrices (not norms / biases / embeddings-norm)."""
    decay, no_decay = [], []
    for name, p in model.named_parameters():
        if not p.requires_grad:
            continue
        if p.dim() >= 2:
            decay.append(p)
        else:
            no_decay.append(p)
    groups = [
        {"params": decay, "weight_decay": cfg.weight_decay},
        {"params": no_decay, "weight_decay": 0.0},
    ]
    kwargs: Dict[str, Any] = dict(lr=cfg.lr, betas=(cfg.beta1, cfg.beta2))
    if torch.cuda.is_available():
        try:
            return torch.optim.AdamW(groups, fused=True, **kwargs)
        except (TypeError, RuntimeError):
            pass
    return torch.optim.AdamW(groups, **kwargs)


def make_grad_scaler(enabled: bool, device_type: str):
    try:
        return torch.amp.GradScaler(device_type, enabled=enabled)
    except (AttributeError, TypeError):
        return torch.cuda.amp.GradScaler(enabled=enabled)


def unwrap(model: nn.Module) -> nn.Module:
    return getattr(model, "_orig_mod", model)


@torch.no_grad()
def estimate_loss(
    model: nn.Module,
    data: torch.Tensor,
    block_size: int,
    batch_size: int,
    device: torch.device,
    ctx,
    eval_iters: int,
) -> float:
    model.eval()
    losses = torch.zeros(eval_iters)
    for i in range(eval_iters):
        x, y = get_batch(data, block_size, batch_size, device)
        with ctx:
            _, loss = model(x, targets=y)
        losses[i] = loss.detach().float().cpu()
    model.train()
    return losses.mean().item()


def save_checkpoint(
    path: str,
    model: nn.Module,
    optimizer: Optional[torch.optim.Optimizer],
    step: int,
    model_args: ModelArgs,
    train_cfg: TrainConfig,
    tokenizer: CharTokenizer,
    best_val: float,
):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    torch.save(
        {
            "model": unwrap(model).state_dict(),
            "optimizer": optimizer.state_dict() if optimizer is not None else None,
            "step": step,
            "best_val": best_val,
            "model_args": asdict(model_args),
            "train_config": asdict(train_cfg),
            "tokenizer": tokenizer.state_dict(),
            "format_version": 1,
        },
        path,
    )


def load_checkpoint(path: str, device: torch.device):
    ckpt = torch.load(path, map_location=device, weights_only=False)
    mcfg = ModelArgs(**ckpt["model_args"])
    model = Transformer(mcfg)
    model.load_state_dict(ckpt["model"])
    model.to(device)
    model.eval()
    tokenizer = CharTokenizer.from_state_dict(ckpt["tokenizer"])
    return model, tokenizer, mcfg, ckpt


# 6. The training loop
def train(
    model: Transformer,
    tokenizer: CharTokenizer,
    train_data: torch.Tensor,
    val_data: torch.Tensor,
    mcfg: ModelArgs,
    tcfg: TrainConfig,
) -> Transformer:
    device = resolve_device(tcfg.device)
    device_type = device.type
    ptdtype = resolve_dtype(tcfg.dtype, device)

    model.to(device)
    model.train()

    use_amp = device_type == "cuda" and ptdtype in (torch.bfloat16, torch.float16)
    ctx = (
        torch.autocast(device_type=device_type, dtype=ptdtype)
        if use_amp
        else contextlib.nullcontext()
    )
    use_scaler = use_amp and ptdtype == torch.float16
    scaler = make_grad_scaler(use_scaler, device_type)

    optimizer = build_optimizer(model, tcfg)

    block_size = min(mcfg.max_seq_len, len(train_data) - 2)
    best_val = float("inf")
    ckpt_path = os.path.join(tcfg.out_dir, "ckpt.pt")
    best_path = os.path.join(tcfg.out_dir, "ckpt_best.pt")

    print("=" * 78)
    print("TRAINING")
    print("=" * 78)
    print(f"  device          : {device}   (amp dtype: {ptdtype if use_amp else 'fp32'})")
    print(f"  parameters      : {model.num_params:,} total "
          f"({model.num_params_non_embedding:,} non-embedding)")
    print(f"  vocab size      : {tokenizer.vocab_size}")
    print(f"  tokens          : {len(train_data):,} train / {len(val_data):,} val")
    print(f"  context length  : {block_size}")
    print(f"  steps           : {tcfg.max_steps}  "
          f"(batch {tcfg.batch_size} x accum {tcfg.grad_accum_steps})")
    print("=" * 78)

    t0 = time.time()
    tokens_per_step = tcfg.batch_size * tcfg.grad_accum_steps * block_size

    for step in range(tcfg.max_steps + 1):
        # ---- periodic evaluation / checkpointing -------------------------
        if step % tcfg.eval_interval == 0 or step == tcfg.max_steps:
            val_loss = estimate_loss(
                model, val_data, block_size, tcfg.batch_size, device, ctx, tcfg.eval_iters
            )
            train_loss = estimate_loss(
                model, train_data, block_size, tcfg.batch_size, device, ctx, tcfg.eval_iters
            )
            flag = ""
            if val_loss < best_val:
                best_val = val_loss
                save_checkpoint(best_path, model, optimizer, step, mcfg, tcfg, tokenizer, best_val)
                flag = "  <- best"
            print(
                f"[eval] step {step:6d} | train {train_loss:.4f} | val {val_loss:.4f} "
                f"| ppl {math.exp(min(val_loss, 20)):8.2f}{flag}"
            )
            save_checkpoint(ckpt_path, model, optimizer, step, mcfg, tcfg, tokenizer, best_val)

        if step == tcfg.max_steps:
            break

        # ---- learning rate schedule --------------------------------------
        lr = get_lr(step, tcfg)
        for g in optimizer.param_groups:
            g["lr"] = lr

        # ---- forward / backward with gradient accumulation ---------------
        optimizer.zero_grad(set_to_none=True)
        total_loss = 0.0
        for _ in range(tcfg.grad_accum_steps):
            x, y = get_batch(train_data, block_size, tcfg.batch_size, device)
            with ctx:
                _, loss = model(x, targets=y)
                loss = loss / tcfg.grad_accum_steps
            scaler.scale(loss).backward()
            total_loss += loss.detach().float().item()

        if tcfg.grad_clip > 0:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), tcfg.grad_clip)

        scaler.step(optimizer)
        scaler.update()

        # ---- logging -----------------------------------------------------
        if step % tcfg.log_interval == 0:
            elapsed = time.time() - t0
            tps = tokens_per_step * (step + 1) / max(elapsed, 1e-6)
            print(
                f"step {step:6d} | loss {total_loss:.4f} | lr {lr:.2e} "
                f"| {elapsed:6.1f}s | {tps/1000:6.1f}k tok/s"
            )

    print("=" * 78)
    print(f"Training complete. Best val loss: {best_val:.4f} "
          f"(ppl {math.exp(min(best_val, 20)):.2f})")
    print(f"Checkpoints: {ckpt_path}  |  {best_path}")
    print("=" * 78)
    return model


# 7. Inference / sampling
def apply_repetition_penalty(
    logits: torch.Tensor, prev_tokens: torch.Tensor, penalty: float
) -> torch.Tensor:
    if penalty == 1.0:
        return logits
    score = torch.gather(logits, 1, prev_tokens)
    score = torch.where(score < 0, score * penalty, score / penalty)
    return logits.scatter(1, prev_tokens, score)


@torch.no_grad()
def sample_next_token(
    logits: torch.Tensor,
    temperature: float = 1.0,
    top_k: Optional[int] = None,
    top_p: Optional[float] = None,
    prev_tokens: Optional[torch.Tensor] = None,
    repetition_penalty: float = 1.0,
    generator: Optional[torch.Generator] = None,
) -> torch.Tensor:
    logits = logits.float()

    if prev_tokens is not None and repetition_penalty != 1.0:
        logits = apply_repetition_penalty(logits, prev_tokens, repetition_penalty)

    if temperature <= 0.0:                      # greedy
        return logits.argmax(dim=-1, keepdim=True)

    logits = logits / temperature

    if top_k is not None and top_k > 0:
        k = min(top_k, logits.size(-1))
        kth = torch.topk(logits, k, dim=-1).values[:, [-1]]
        logits = logits.masked_fill(logits < kth, float("-inf"))

    if top_p is not None and 0.0 < top_p < 1.0:
        sorted_logits, sorted_idx = torch.sort(logits, descending=True, dim=-1)
        probs = F.softmax(sorted_logits, dim=-1)
        cumulative = probs.cumsum(dim=-1)
        remove = (cumulative - probs) > top_p
        sorted_logits = sorted_logits.masked_fill(remove, float("-inf"))
        logits = torch.full_like(logits, float("-inf")).scatter(-1, sorted_idx, sorted_logits)

    probs = F.softmax(logits, dim=-1)
    return torch.multinomial(probs, num_samples=1, generator=generator)


@torch.no_grad()
def generate(
    model: Transformer,
    idx: torch.Tensor,
    max_new_tokens: int = 200,
    temperature: float = 1.0,
    top_k: Optional[int] = None,
    top_p: Optional[float] = None,
    repetition_penalty: float = 1.0,
    use_cache: bool = True,
    seed: Optional[int] = None,
    stop_tokens: Optional[set] = None,
) -> torch.Tensor:
    """Autoregressive generation with an optional KV cache."""
    model.eval()
    device = idx.device
    max_ctx = model.params.max_seq_len

    generator = None
    if seed is not None:
        generator = torch.Generator(device=device).manual_seed(seed)

    caches = [KVCache() for _ in model.layers] if use_cache else None

    # ---- prefill ---------------------------------------------------------
    if use_cache:
        logits, _ = model(idx, start_pos=0, caches=caches)
    else:
        logits, _ = model(idx[:, -max_ctx:], start_pos=0)

    out = idx
    for _ in range(max_new_tokens):
        next_tok = sample_next_token(
            logits[:, -1, :], temperature, top_k, top_p,
            prev_tokens=out, repetition_penalty=repetition_penalty, generator=generator,
        )
        out = torch.cat([out, next_tok], dim=1)

        if stop_tokens and int(next_tok.item()) in stop_tokens:
            break

        if use_cache:
            pos = caches[0].size
            if pos + 1 > max_ctx:
                break
            logits, _ = model(next_tok, start_pos=pos, caches=caches)
        else:
            logits, _ = model(out[:, -max_ctx:], start_pos=0)

    return out


# 8. CLI
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Single-file LLaMA-style Transformer: train + inference.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--mode", choices=["train", "generate", "both"], default="both")
    p.add_argument("--data", type=str, default=None,
                   help="Path to a UTF-8 text file. Defaults to the built-in corpus.")
    p.add_argument("--out-dir", type=str, default="out")
    p.add_argument("--ckpt", type=str, default=None,
                   help="Checkpoint to load for --mode generate (default: out/ckpt_best.pt)")

    # Model
    p.add_argument("--dim", type=int, default=256)
    p.add_argument("--n-layers", type=int, default=6)
    p.add_argument("--n-heads", type=int, default=8)
    p.add_argument("--n-kv-heads", type=int, default=4)
    p.add_argument("--max-seq-len", type=int, default=256)
    p.add_argument("--dropout", type=float, default=0.0)
    p.add_argument("--no-tie-embeddings", action="store_true")

    # Training
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--grad-accum", type=int, default=1)
    p.add_argument("--max-steps", type=int, default=1500)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--min-lr", type=float, default=1e-4)
    p.add_argument("--warmup-steps", type=int, default=100)
    p.add_argument("--weight-decay", type=float, default=0.1)
    p.add_argument("--grad-clip", type=float, default=1.0)
    p.add_argument("--eval-interval", type=int, default=100)
    p.add_argument("--eval-iters", type=int, default=40)
    p.add_argument("--log-interval", type=int, default=10)
    p.add_argument("--device", type=str, default="auto")
    p.add_argument("--dtype", type=str, default="auto",
                   choices=["auto", "bfloat16", "float16", "float32"])
    p.add_argument("--compile", action="store_true")
    p.add_argument("--seed", type=int, default=1337)

    # Sampling
    p.add_argument("--prompt", type=str, default="The ")
    p.add_argument("--max-new-tokens", type=int, default=300)
    p.add_argument("--temperature", type=float, default=0.8)
    p.add_argument("--top-k", type=int, default=40)
    p.add_argument("--top-p", type=float, default=None)
    p.add_argument("--repetition-penalty", type=float, default=1.1)
    p.add_argument("--no-kv-cache", action="store_true")
    p.add_argument("--num-samples", type=int, default=3)

    return p.parse_args()


def build_model_and_tokenizer(args, text: str) -> Tuple[Transformer, CharTokenizer, ModelArgs]:
    tokenizer = CharTokenizer(text=text)
    mcfg = ModelArgs(
        dim=args.dim,
        n_layers=args.n_layers,
        n_heads=args.n_heads,
        n_kv_heads=args.n_kv_heads,
        vocab_size=tokenizer.vocab_size,
        max_seq_len=args.max_seq_len,
        dropout=args.dropout,
        tie_embeddings=not args.no_tie_embeddings,
    )
    model = Transformer(mcfg)
    return model, tokenizer, mcfg


def build_train_config(args) -> TrainConfig:
    return TrainConfig(
        batch_size=args.batch_size,
        grad_accum_steps=args.grad_accum,
        max_steps=args.max_steps,
        eval_interval=args.eval_interval,
        eval_iters=args.eval_iters,
        log_interval=args.log_interval,
        lr=args.lr,
        min_lr=args.min_lr,
        warmup_steps=args.warmup_steps,
        weight_decay=args.weight_decay,
        grad_clip=args.grad_clip,
        device=args.device,
        dtype=args.dtype,
        compile=args.compile,
        out_dir=args.out_dir,
        seed=args.seed,
    )


def run_generation(model, tokenizer, args, prompt: Optional[str] = None, label: str = ""):
    device = next(model.parameters()).device
    prompt = prompt if prompt is not None else args.prompt
    ids = tokenizer.encode(prompt)
    if not ids:
        ids = [0]
    idx = torch.tensor([ids], dtype=torch.long, device=device)

    if label:
        print(f"\n--- {label} ---")
    for i in range(args.num_samples):
        t0 = time.time()
        out = generate(
            model,
            idx,
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
            top_k=args.top_k,
            top_p=args.top_p,
            repetition_penalty=args.repetition_penalty,
            use_cache=not args.no_kv_cache,
            seed=args.seed + i,
        )
        text = tokenizer.decode(out[0])
        dt = time.time() - t0
        n_new = out.shape[1] - idx.shape[1]
        print(f"\n[sample {i + 1}]  ({n_new} tokens in {dt:.2f}s, "
              f"{n_new / max(dt, 1e-6):.1f} tok/s)")
        print(text)
    print()


def main():
    args = parse_args()
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)

    device = resolve_device(args.device)

    # ---------------------------------------------------------------- data
    text = load_text(args.data)
    model, tokenizer, mcfg = build_model_and_tokenizer(args, text)

    if args.mode in ("train", "both"):
        data = torch.tensor(tokenizer.encode(text), dtype=torch.long)
        if len(data) < mcfg.max_seq_len + 2:
            raise SystemExit(
                f"Corpus encodes to {len(data)} tokens, which is too small for "
                f"max_seq_len={mcfg.max_seq_len}. Provide a larger --data file "
                f"or lower --max-seq-len."
            )
        train_data, val_data = split_train_val(data, val_frac=0.1)

        if args.compile:
            try:
                print("Compiling model with torch.compile ...")
                model = torch.compile(model)   # noqa: F821
            except Exception as e:             # pragma: no cover
                print(f"torch.compile unavailable ({e}); continuing eagerly.")

        model = train(model, tokenizer, train_data, val_data, mcfg, build_train_config(args))
        model.eval()

        if args.mode == "both":
            run_generation(model, tokenizer, args,
                           label="Samples from the freshly trained model")

    if args.mode == "generate":
        ckpt_path = args.ckpt or os.path.join(args.out_dir, "ckpt_best.pt")
        if not os.path.exists(ckpt_path):
            raise SystemExit(
                f"No checkpoint found at '{ckpt_path}'. Train first or pass --ckpt."
            )
        print(f"Loading checkpoint: {ckpt_path}")
        model, tokenizer, mcfg, ckpt = load_checkpoint(ckpt_path, device)
        print(f"  step {ckpt.get('step')} | best val {ckpt.get('best_val'):.4f} "
              f"| params {model.num_params:,}")
        run_generation(model, tokenizer, args, label="Samples from checkpoint")


if __name__ == "__main__":
    main()